[package]
name = "kangarootwelve-xkcp"
version = "0.1.0"
authors = ["Jack O'Connor <oconnor663@gmail.com>"]
license-file = "LICENSE"
edition = "2018"

[dependencies]

[dev-dependencies]
hex = "0.4.2"
