name: tests

on:
  push:
    branches:
      - "*"
    # not on tags
  pull_request:

jobs:
  cargo_tests:
    name: ${{ matrix.channel }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        channel: [stable, beta, nightly]

    steps:
    - uses: actions/checkout@v1
    - run: sudo apt-get update
    - run: sudo apt-get install xsltproc gcc-multilib
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ format('{0}-{1}', matrix.channel, matrix.target.toolchain) }}
        profile: minimal
        override: true
    - run: cargo test
    - run: rustup target add i686-unknown-linux-gnu
    - run: CFLAGS=-m32 cargo test --target i686-unknown-linux-gnu
    # Test benchmarks. RUSTC_BOOTSTRAP=1 lets this run on non-nightly toolchains.
    - run: cargo test --benches
      env:
        RUSTC_BOOTSTRAP: 1
